import JSZip from 'jszip'
import { saveAs } from 'file-saver'
import type { Slide, SizePreset } from './types'
import { SIZE_PRESETS } from './presets'
import { renderToCanvas, preloadImage } from './canvas-renderer'

async function renderSlideToBlob(slide: Slide, preset: SizePreset): Promise<Blob> {
  if (slide.screenshotDataUrl) await preloadImage(slide.screenshotDataUrl)
  const canvas = document.createElement('canvas')
  renderToCanvas(canvas, slide, preset)
  return new Promise<Blob>((resolve, reject) => {
    canvas.toBlob(b => b ? resolve(b) : reject(new Error('toBlob failed')), 'image/png')
  })
}

export async function downloadSingle(
  slide: Slide,
  preset: SizePreset,
  filename = 'screenshot.png',
): Promise<void> {
  const blob = await renderSlideToBlob(slide, preset)
  saveAs(blob, filename)
}

// Export every slide at a specific preset
export async function renderAllSlidesToBlobs(
  slides: Slide[],
  preset: SizePreset,
): Promise<Array<{ name: string; blob: Blob }>> {
  const results: Array<{ name: string; blob: Blob }> = []
  for (let i = 0; i < slides.length; i++) {
    const blob = await renderSlideToBlob(slides[i], preset)
    results.push({ name: `slide_${i + 1}.png`, blob })
  }
  return results
}

export interface ExportSize {
  preset: SizePreset
  enabled: boolean
}

export function defaultExportSizes(): ExportSize[] {
  return SIZE_PRESETS.map(p => ({
    preset: p,
    // Enable the main required sizes by default
    enabled: [
      'iPhone 6.9"', 'iPhone 6.5"', 'iPad Pro 13"',
      'Google Phone', 'Feature Graphic',
    ].includes(p.label),
  }))
}

// Full professional ZIP: organised by platform > device > slide
export async function buildFullExportZip(
  slides: Slide[],
  exportSizes: ExportSize[],
  appName: string,
  onProgress?: (done: number, total: number) => void,
): Promise<Blob> {
  const zip = new JSZip()
  const enabledSizes = exportSizes.filter(s => s.enabled)
  const total = enabledSizes.length * slides.length
  let done = 0

  for (const { preset } of enabledSizes) {
    const platform = preset.platform === 'apple' ? 'Apple' : preset.platform === 'google' ? 'Google' : 'Watch'
    const deviceSlug = preset.label.replace(/[^a-z0-9]/gi, '_').replace(/_+/g, '_').toLowerCase()
    const folder = zip.folder(`${platform}/${deviceSlug}`)!

    for (let i = 0; i < slides.length; i++) {
      const blob = await renderSlideToBlob(slides[i], preset)
      const buf = await blob.arrayBuffer()
      folder.file(`slide_${i + 1}.png`, buf)
      done++
      onProgress?.(done, total)
    }
  }

  // Add a README
  zip.file('README.txt', buildReadme(enabledSizes, appName))

  return zip.generateAsync({ type: 'blob', compression: 'DEFLATE', compressionOptions: { level: 6 } })
}

export async function downloadFullExportZip(
  slides: Slide[],
  exportSizes: ExportSize[],
  appName: string,
  onProgress?: (done: number, total: number) => void,
): Promise<Blob> {
  const blob = await buildFullExportZip(slides, exportSizes, appName, onProgress)
  const safe = appName.replace(/[^a-z0-9]/gi, '_').toLowerCase()
  saveAs(blob, `${safe}_screenshots.zip`)
  return blob
}

function buildReadme(sizes: ExportSize[], appName: string): string {
  const lines = [
    `Screenshots for: ${appName}`,
    `Generated by IndieOS — ${new Date().toLocaleDateString()}`,
    '',
    'FOLDER STRUCTURE',
    '================',
  ]

  const groups: Record<string, SizePreset[]> = {}
  for (const { preset } of sizes) {
    const p = preset.platform === 'apple' ? 'Apple App Store' : preset.platform === 'google' ? 'Google Play' : 'Apple Watch'
    if (!groups[p]) groups[p] = []
    groups[p].push(preset)
  }

  for (const [platform, presets] of Object.entries(groups)) {
    lines.push(``, `${platform}:`)
    for (const p of presets) {
      lines.push(`  ${p.label} — ${p.width}×${p.height}px`)
    }
  }

  lines.push(``, 'UPLOAD INSTRUCTIONS', '===================')
  lines.push(`Apple App Store Connect:`)
  lines.push(`  1. Go to your app > App Store tab > Screenshots`)
  lines.push(`  2. Upload iPhone 6.9" screenshots (required)`)
  lines.push(`  3. Upload iPad Pro 13" screenshots (if supporting iPad)`)
  lines.push(``)
  lines.push(`Google Play Console:`)
  lines.push(`  1. Go to Store listing > Graphics`)
  lines.push(`  2. Upload Phone screenshots (1080×1920)`)
  lines.push(`  3. Upload Feature graphic (1024×500)`)
  lines.push(`  4. Upload Tablet screenshots if supporting tablets`)

  return lines.join('\n')
}
